# Generated by Django 4.1.2 on 2022-10-09 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="App",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=100)),
                ("text", models.TextField()),
                (
                    "degree",
                    models.CharField(
                        choices=[
                            ("0", "0%"),
                            ("10", "10%"),
                            ("20", "20%"),
                            ("30", "30%"),
                            ("40", "40%"),
                            ("50", "50%"),
                            ("60", "60%"),
                            ("70", "70%"),
                            ("80", "80%"),
                            ("90", "90%"),
                            ("100", "100%"),
                            ("120", "limit-break"),
                        ],
                        max_length=100,
                        null=True,
                    ),
                ),
            ],
        ),
    ]
